In [58]:
## Problem 1 
#Matrix Manipulations
#Lets first create a matrix and perform some manipulations of it.
#Using numpy's matrix data structure, define the following matricies:
import math
import numpy as np
A=np.array([[3,5,9],[3,3,4],[5,9,17]])
B=np.array([[2],[1],[4]])
print("A=",A)
print("B=",B)
x=np.linalg.solve(A,B)
print("Solution x is",x)

A= [[ 3  5  9]
 [ 3  3  4]
 [ 5  9 17]]
B= [[2]
 [1]
 [4]]
Solution x is [[ 1.]
 [-2.]
 [ 1.]]


In [55]:
# Problem 2
#Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
#arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
#arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = sum(arrayOne,arrayTwo)
print("Sum of two arrays is \n")
print(resultArray)
print("The square of each eac element")
squareArray=resultArray*resultArray
print(squareArray)

Sum of two arrays is 

[[41 57 60]
 [30 31 37]]
Te square of each eac element
[[1681 3249 3600]
 [ 900  961 1369]]


In [61]:
# Problem 3
#Print max from axis 0 and min from axis 1 from the following 2-D array.
#sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
#maximam from axis=0
maxfromaxis0=np.max(sampleArray, axis=0)
print("maxfromaxis0=",maxfromaxis0)
#minimam from axis=1
minfromaxis1=np.min(sampleArray,axis=1)
print("minfromaxis1=",minfromaxis1)

maxfromaxis0= [82 94 73]
minfromaxis1= [34 12 53]


In [28]:
## Problem 4
#Get the positions where elements of a and b match\Input:  a = np.array([1,2,3,2,3,4,3,4,5,6])\b = np.array([7,2,10,2,7,4,9,4,9,8])\Desired Output: array([1, 3, 5, 7])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [41]:
# Problem 5
#Given a&b Obtain c and d
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a, b), axis=0)
print("c=",c)
d=np.concatenate((a, b), axis=1)
print("d=",d)


c= [[1 2]
 [3 4]
 [5 6]
 [7 8]]
d= [[1 2 5 6]
 [3 4 7 8]]
